# Model configuration
model_name: "google/mt5-base"
max_length: 512
num_beams: 5
temperature: 0.8
do_sample: true
top_k: 50
top_p: 0.95
length_penalty: 1.0
repetition_penalty: 1.2

# Few-shot prompting configuration
use_few_shot: true
num_examples: 3

# Prompt tuning configuration
use_prompt_tuning: false
num_virtual_tokens: 10

# RAG configuration
use_rag: false
rag_index_path: null

# Evaluation configuration
metrics:
  - bleu
  - rouge
  - bert_score
  - style_consistency 